#!/usr/bin/env python3
"""Generate DDR node golden for wf_global_topk_integrated_00 counterexample.

Uses schema-locked NodeRecordV1 pack (cue = 0xDDFE_0000 + node_id) so
a7ng_ddr_feed_axi_bridge expected_node_beat() matches — beat_mm must be 0.
Scores are TermGen+scorer totals for TB query cues (same as ddr_wavefront_00).
"""
from __future__ import annotations

from pathlib import Path

QC = 0xA5A50F0F12345678
RC = 0x0F1E2D3C4B5A6978
IC = 0x1111222233334444
CC = 0xDEADBEEFCAFE0001
PC = 0x00FF00FF00FF00FF
PRIOR = 3
MASK64 = (1 << 64) - 1
TOTAL = 32


def rotl(x: int, k: int, w: int = 64) -> int:
    k %= w
    return ((x << k) | (x >> (w - k))) & MASK64


def pop64(x: int) -> int:
    return (x & MASK64).bit_count()


def sim8(a: int, b: int) -> int:
    return 64 - pop64(a ^ b)


def contra8(a: int, b: int, mask: int) -> int:
    return pop64((a ^ b) & mask) >> 1


def score_nid(nid: int) -> int:
    cue32 = (0xDDFE_0000 + nid) & 0xFFFFFFFF
    n = (cue32 << 32) | cue32
    q, r, i, ctx, p = QC, RC, IC, CC, PC
    path_expect = rotl(q ^ n, 8)
    return (
        sim8(q, n)
        + sim8(i, rotl(n, 16))
        + sim8(q ^ rotl(r, 1), n)
        + sim8(ctx, rotl(n, 32))
        + sim8(p, path_expect)
        + PRIOR
        - contra8(q, n, p)
    )


def topk8(nodes: list[tuple[int, int]]) -> list[tuple[int, int]]:
    return sorted(nodes, key=lambda x: (-x[1], x[0]))[:8]


def main() -> int:
    all_scored = [(nid, score_nid(nid)) for nid in range(TOTAL)]
    w1 = all_scored[:16]
    w2 = all_scored[16:]
    w1_top = topk8(w1)
    w2_top = topk8(w2)
    exp_global = topk8(w1_top + w2_top)
    exp_pw = w2_top

    if exp_global == exp_pw:
        print("GEN_FAIL global equals per-wave-only")
        return 2
    if sum(1 for a, b in zip(exp_global, exp_pw) if a != b) == 0:
        print("GEN_FAIL no per-wave divergence")
        return 3

    w1_8th = w1_top[7]
    w1_8th_in_global = any(nid == w1_8th[0] for nid, _ in exp_global)
    if w1_8th_in_global:
        print(f"GEN_FAIL w1_8th {w1_8th} still in global {exp_global}")
        return 4

    root = Path(__file__).resolve().parents[2]
    out = root / "tests" / "xsim" / "tb_a7ng_wf_global_topk_integrated_golden.svh"
    lines = [
        "// AUTO-GENERATED by gen_wf_global_topk_integrated_nodes.py — do not hand-edit",
        f"localparam int WFGI_N = {TOTAL};",
        "localparam logic [31:0] WFGI_EXP_GID [0:7] = '{",
    ]
    lines.append(",\n".join(f"  32'd{nid}" for nid, _ in exp_global))
    lines.append("};")
    lines.append("localparam logic signed [15:0] WFGI_EXP_GSCORE [0:7] = '{")
    lines.append(",\n".join(f"  16'sd{score}" for _, score in exp_global))
    lines.append("};")
    lines.append("localparam logic [31:0] WFGI_EXP_PWID [0:7] = '{")
    lines.append(",\n".join(f"  32'd{nid}" for nid, _ in exp_pw))
    lines.append("};")
    lines.append("localparam logic signed [15:0] WFGI_EXP_PWSCORE [0:7] = '{")
    lines.append(",\n".join(f"  16'sd{score}" for _, score in exp_pw))
    lines.append("};")
    lines.append(f"localparam logic [31:0] WFGI_W1_8TH_ID = 32'd{w1_8th[0]};")
    lines.append(f"localparam logic signed [15:0] WFGI_W1_8TH_SCORE = 16'sd{w1_8th[1]};")
    lines.append("// W1 8th displaced from G_final by cross-wave merge (schema-locked node_id 0..31)")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"GEN_PASS w1_8th={w1_8th} displaced global={exp_global}")
    print(f"svh={out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
