// AUTO-GENERATED by gen_wf_global_topk_integrated_nodes.py — do not hand-edit
localparam int WFGI_N = 32;
localparam logic [31:0] WFGI_EXP_GID [0:7] = '{
  32'd9,
  32'd11,
  32'd25,
  32'd27,
  32'd13,
  32'd15,
  32'd29,
  32'd31
};
localparam logic signed [15:0] WFGI_EXP_GSCORE [0:7] = '{
  16'sd165,
  16'sd165,
  16'sd165,
  16'sd165,
  16'sd163,
  16'sd163,
  16'sd163,
  16'sd163
};
localparam logic [31:0] WFGI_EXP_PWID [0:7] = '{
  32'd25,
  32'd27,
  32'd29,
  32'd31,
  32'd17,
  32'd19,
  32'd24,
  32'd26
};
localparam logic signed [15:0] WFGI_EXP_PWSCORE [0:7] = '{
  16'sd165,
  16'sd165,
  16'sd163,
  16'sd163,
  16'sd162,
  16'sd162,
  16'sd161,
  16'sd161
};
localparam logic [31:0] WFGI_W1_8TH_ID = 32'd10;
localparam logic signed [15:0] WFGI_W1_8TH_SCORE = 16'sd161;
// W1 8th displaced from G_final by cross-wave merge (schema-locked node_id 0..31)
