// tb_a7ng_frontier_shootout.sv — XSim RTL check for arms A/B/C (same workload)
// Primary metrics table comes from frontier_shootout_oracle.py.
// This TB proves B/C RTL match Python golden; A (DEPTH=4) is smoke+overflow sanity.
// Push XOR pop. Does not touch a7ng-topk-global-v1.
`timescale 1ns / 1ps

module tb_a7ng_frontier_shootout;
  localparam int N_QUERIES = 64;
  localparam int PUSHES    = 48;
  localparam int CAP       = 64;

  logic clk, rst_n;

  // Arm A — bucket DEPTH=4 → CAP=64
  logic a_push, a_pop, a_pv, a_ovf, a_rdy;
  logic signed [15:0] a_si, a_so;
  logic [31:0] a_idi, a_ido;
  logic [7:0] a_cnt;
  a7ng_frontier_buckets #(.NBINS(16), .DEPTH(4)) dut_a (
    .clk(clk), .rst_n(rst_n),
    .push_i(a_push), .score_i(a_si), .id_i(a_idi),
    .pop_i(a_pop), .pop_valid_o(a_pv), .score_o(a_so), .id_o(a_ido),
    .overflow_o(a_ovf), .ready_o(a_rdy), .count_o(a_cnt)
  );

  // Arm B — systolic PQ
  logic b_push, b_pop, b_pv, b_ovf, b_rdy;
  logic signed [15:0] b_si, b_so;
  logic [31:0] b_idi, b_ido;
  logic [7:0] b_cnt;
  a7ng_frontier_systolic_pq #(.DEPTH(64)) dut_b (
    .clk(clk), .rst_n(rst_n),
    .push_i(b_push), .score_i(b_si), .id_i(b_idi),
    .pop_i(b_pop), .pop_valid_o(b_pv), .score_o(b_so), .id_o(b_ido),
    .overflow_o(b_ovf), .ready_o(b_rdy), .count_o(b_cnt)
  );

  // Arm C — two-level
  logic c_push, c_pop, c_pv, c_ovf, c_rdy;
  logic signed [15:0] c_si, c_so;
  logic [31:0] c_idi, c_ido;
  logic [7:0] c_cnt;
  a7ng_frontier_twolevel #(.N_LOCAL(4), .LOCAL_DEPTH(16)) dut_c (
    .clk(clk), .rst_n(rst_n),
    .push_i(c_push), .score_i(c_si), .id_i(c_idi),
    .pop_i(c_pop), .pop_valid_o(c_pv), .score_o(c_so), .id_o(c_ido),
    .overflow_o(c_ovf), .ready_o(c_rdy), .count_o(c_cnt)
  );

  initial clk = 0;
  always #5 clk = ~clk;

  // Workload + golden (generated by frontier_shootout_oracle.py)
  integer vf, gbf, gcf;
  integer qi, npush, npop_b, npop_c, ovf_b_exp, ovf_c_exp;
  integer score_i, id_i;
  integer g_score, g_id;
  integer fails;
  integer b_ovf_cnt, c_ovf_cnt, a_ovf_cnt;
  integer b_pop_cnt, c_pop_cnt;
  integer dummy_qi;
  integer ch;
  reg [31:0] qseed_hex;

  task automatic skip_line(input integer fd);
    begin
      ch = $fgetc(fd);
      while (ch != "\n" && ch >= 0) ch = $fgetc(fd);
    end
  endtask

  task automatic idle_bus;
    begin
      a_push = 0; a_pop = 0; a_si = 0; a_idi = 0;
      b_push = 0; b_pop = 0; b_si = 0; b_idi = 0;
      c_push = 0; c_pop = 0; c_si = 0; c_idi = 0;
    end
  endtask

  task automatic do_reset;
    begin
      rst_n = 0;
      idle_bus();
      repeat (4) @(posedge clk);
      rst_n = 1;
      @(posedge clk);
    end
  endtask

  task automatic push_all(input integer s, input integer id);
    begin
      @(negedge clk);
      a_si = s[15:0]; a_idi = id; a_push = 1; a_pop = 0;
      b_si = s[15:0]; b_idi = id; b_push = 1; b_pop = 0;
      c_si = s[15:0]; c_idi = id; c_push = 1; c_pop = 0;
      @(posedge clk);
      #1;
      if (a_ovf) a_ovf_cnt = a_ovf_cnt + 1;
      if (b_ovf) b_ovf_cnt = b_ovf_cnt + 1;
      if (c_ovf) c_ovf_cnt = c_ovf_cnt + 1;
      idle_bus();
    end
  endtask

  task automatic pop_once;
    begin
      @(negedge clk);
      a_push = 0; a_pop = 1;
      b_push = 0; b_pop = 1;
      c_push = 0; c_pop = 1;
      @(posedge clk);
      #1;
      if (b_pv) begin
        if ($fscanf(gbf, "%d %d\n", g_score, g_id) != 2) begin
          $display("FAIL B golden underrun q=%0d", qi);
          fails = fails + 1;
        end else if (b_so !== g_score[15:0] || b_ido !== g_id[31:0]) begin
          $display("FAIL B mismatch q=%0d got s=%0d id=%0d exp s=%0d id=%0d",
                   qi, b_so, b_ido, g_score, g_id);
          fails = fails + 1;
        end
        b_pop_cnt = b_pop_cnt + 1;
      end
      if (c_pv) begin
        if ($fscanf(gcf, "%d %d\n", g_score, g_id) != 2) begin
          $display("FAIL C golden underrun q=%0d", qi);
          fails = fails + 1;
        end else if (c_so !== g_score[15:0] || c_ido !== g_id[31:0]) begin
          $display("FAIL C mismatch q=%0d got s=%0d id=%0d exp s=%0d id=%0d",
                   qi, c_so, c_ido, g_score, g_id);
          fails = fails + 1;
        end
        c_pop_cnt = c_pop_cnt + 1;
      end
      idle_bus();
    end
  endtask

  initial begin
    fails = 0;
    a_ovf_cnt = 0; b_ovf_cnt = 0; c_ovf_cnt = 0;
    b_pop_cnt = 0; c_pop_cnt = 0;
    idle_bus();

    vf  = $fopen("../../results/A7-NATIVE-GRAPH/FRONTIER-SHOOTOUT/workload_vectors.txt", "r");
    gbf = $fopen("../../results/A7-NATIVE-GRAPH/FRONTIER-SHOOTOUT/golden_B_pops.txt", "r");
    gcf = $fopen("../../results/A7-NATIVE-GRAPH/FRONTIER-SHOOTOUT/golden_C_pops.txt", "r");
    if (vf == 0 || gbf == 0 || gcf == 0) begin
      $display("FAIL open vectors (run frontier_shootout_oracle.py first)");
      $finish;
    end
    // skip header lines
    skip_line(vf);
    skip_line(gbf);
    skip_line(gcf);

    for (qi = 0; qi < N_QUERIES; qi = qi + 1) begin
      do_reset();
      if ($fscanf(vf, "Q %d 0x%x %d\n", dummy_qi, qseed_hex, npush) != 3) begin
        $display("FAIL vector hdr q=%0d", qi);
        fails = fails + 1;
      end else if ($fscanf(gbf, "Q %d %d %d\n", dummy_qi, npop_b, ovf_b_exp) != 3) begin
        $display("FAIL goldB hdr q=%0d", qi);
        fails = fails + 1;
      end else if ($fscanf(gcf, "Q %d %d %d\n", dummy_qi, npop_c, ovf_c_exp) != 3) begin
        $display("FAIL goldC hdr q=%0d", qi);
        fails = fails + 1;
      end else begin
        b_ovf_cnt = 0; c_ovf_cnt = 0; a_ovf_cnt = 0;
        b_pop_cnt = 0; c_pop_cnt = 0;

        for (int p = 0; p < npush; p = p + 1) begin
          if ($fscanf(vf, "%d %d\n", score_i, id_i) != 2) begin
            $display("FAIL vector body q=%0d p=%0d", qi, p);
            fails = fails + 1;
          end
          push_all(score_i, id_i);
        end

        // Drain until all empty (bounded)
        begin : drain
          integer d;
          for (d = 0; d < CAP + 4; d = d + 1) begin
            if (a_cnt == 0 && b_cnt == 0 && c_cnt == 0) begin
              d = CAP + 3; // exit
            end else begin
              pop_once();
            end
          end
        end

        if (b_pop_cnt !== npop_b) begin
          $display("FAIL B popcount q=%0d got=%0d exp=%0d", qi, b_pop_cnt, npop_b);
          fails = fails + 1;
        end
        if (c_pop_cnt !== npop_c) begin
          $display("FAIL C popcount q=%0d got=%0d exp=%0d", qi, c_pop_cnt, npop_c);
          fails = fails + 1;
        end
        if (b_ovf_cnt !== ovf_b_exp) begin
          $display("FAIL B ovf q=%0d got=%0d exp=%0d", qi, b_ovf_cnt, ovf_b_exp);
          fails = fails + 1;
        end
        if (c_ovf_cnt !== ovf_c_exp) begin
          $display("FAIL C ovf q=%0d got=%0d exp=%0d", qi, c_ovf_cnt, ovf_c_exp);
          fails = fails + 1;
        end
      end
    end

    $fclose(vf); $fclose(gbf); $fclose(gcf);
    if (fails == 0)
      $display("A7NG_FRONTIER_SHOOTOUT_XSIM_PASS queries=%0d", N_QUERIES);
    else
      $display("A7NG_FRONTIER_SHOOTOUT_XSIM_FAIL fails=%0d", fails);
    $finish;
  end
endmodule
