#!/usr/bin/env python3
"""TermGen golden oracle — law a7ng-termgen-v0 (binary HDC/VSA, cue_w=64).

Four feature families must all be present and bit-exact vs RTL:
  Hamming (entity), relation binding, intent/context, path feature.
Prior is memory passthrough; contradiction from masked Hamming bits.

Does NOT claim end-to-end candidates/s. No BOARD_PASS.
"""
from __future__ import annotations

import hashlib
import json
import struct
import sys
from pathlib import Path

LAW_ID = "a7ng-termgen-v0"
CUE_W = 64
SEED = 0xA7622201
N_VEC = 32  # candidate vectors / query bag units (not cycles-as-queries)
MASK64 = (1 << 64) - 1


def rotl(x: int, k: int, w: int = CUE_W) -> int:
    k %= w
    return ((x << k) | (x >> (w - k))) & MASK64


def pop64(x: int) -> int:
    return (x & MASK64).bit_count()


def sim8(a: int, b: int) -> int:
    return 64 - pop64(a ^ b)


def contra8(a: int, b: int, mask: int) -> int:
    return pop64((a ^ b) & mask) >> 1


def termgen(cues: dict) -> dict:
    q = cues["query_cue"]
    n = cues["node_cue"]
    r = cues["relation_cue"]
    i = cues["intent_cue"]
    ctx = cues["context_cue"]
    p = cues["path_cue"]
    prior = int(cues["learned_prior"])
    if prior > 127:
        prior -= 256
    path_expect = rotl(q ^ n, 8)
    return {
        "entity_match": sim8(q, n),
        "intent_match": sim8(i, rotl(n, 16)),
        "relation_match": sim8(q ^ rotl(r, 1), n),
        "context_match": sim8(ctx, rotl(n, 32)),
        "path_confidence": sim8(p, path_expect),
        "learned_prior": prior,
        "contradiction_penalty": contra8(q, n, p),
    }


def u64(seed: int, salt: int) -> int:
    h = hashlib.sha256(struct.pack("<II", seed & 0xFFFFFFFF, salt & 0xFFFFFFFF)).digest()
    return int.from_bytes(h[:8], "little")


def i8(seed: int, salt: int) -> int:
    return (u64(seed, salt) & 0x7F) - 32  # [-32, 95]


def build_bag(seed: int = SEED, n: int = N_VEC) -> list[dict]:
    bag: list[dict] = []
    for v in range(n):
        cues = {
            "cand_id": 0x2000 + v,
            "query_cue": u64(seed, 0x1000 + v),
            "node_cue": u64(seed, 0x2000 + v),
            "relation_cue": u64(seed, 0x3000 + v),
            "intent_cue": u64(seed, 0x4000 + v),
            "context_cue": u64(seed, 0x5000 + v),
            "path_cue": u64(seed, 0x6000 + v),
            "learned_prior": i8(seed, 0x7000 + v),
        }
        if v == 0:
            # identical / bound-aligned → max Hamming + path families
            cues["node_cue"] = cues["query_cue"]
            cues["intent_cue"] = rotl(cues["node_cue"], 16)
            cues["context_cue"] = rotl(cues["node_cue"], 32)
            cues["path_cue"] = rotl(cues["query_cue"] ^ cues["node_cue"], 8)
            cues["learned_prior"] = 7
        elif v == 1:
            cues["node_cue"] = (~cues["query_cue"]) & MASK64
        terms = termgen(cues)
        for fam in (
            "entity_match",
            "relation_match",
            "intent_match",
            "context_match",
            "path_confidence",
        ):
            assert fam in terms, f"missing family {fam}"
        bag.append({"cues": cues, "terms": terms})
    return bag


def sv_s8(v: int) -> str:
    """Emit Vivado-legal signed 8-bit localparam literal."""
    v = int(v)
    if v < 0:
        return f"-8'sd{-v}"
    return f"8'sd{v}"


def emit_sv_include(bag: list[dict], path: Path) -> None:
    """Write localparam tables for XSim TB (hex cues + signed terms)."""
    lines = [
        "// AUTO-GENERATED by termgen_oracle.py — do not hand-edit",
        f"// law={LAW_ID} seed=0x{SEED:08X} n={len(bag)}",
        f"localparam int TG_N = {len(bag)};",
        "localparam logic [63:0] TG_Q   [0:TG_N-1] = '{",
    ]

    def hex_list(key: str) -> str:
        return ",\n".join(f"  64'h{row['cues'][key]:016X}" for row in bag)

    lines.append(hex_list("query_cue"))
    lines.append("};")
    lines.append("localparam logic [63:0] TG_NODE [0:TG_N-1] = '{")
    lines.append(hex_list("node_cue"))
    lines.append("};")
    lines.append("localparam logic [63:0] TG_REL  [0:TG_N-1] = '{")
    lines.append(hex_list("relation_cue"))
    lines.append("};")
    lines.append("localparam logic [63:0] TG_INT  [0:TG_N-1] = '{")
    lines.append(hex_list("intent_cue"))
    lines.append("};")
    lines.append("localparam logic [63:0] TG_CTX  [0:TG_N-1] = '{")
    lines.append(hex_list("context_cue"))
    lines.append("};")
    lines.append("localparam logic [63:0] TG_PATH [0:TG_N-1] = '{")
    lines.append(hex_list("path_cue"))
    lines.append("};")
    lines.append("localparam logic signed [7:0] TG_PRIOR [0:TG_N-1] = '{")
    lines.append(",\n".join(f"  {sv_s8(row['cues']['learned_prior'])}" for row in bag))
    lines.append("};")
    for field in (
        "entity_match",
        "intent_match",
        "relation_match",
        "context_match",
        "path_confidence",
        "learned_prior",
        "contradiction_penalty",
    ):
        uname = field.upper()
        lines.append(f"localparam logic signed [7:0] TG_GOLD_{uname} [0:TG_N-1] = '{{")
        lines.append(",\n".join(f"  {sv_s8(row['terms'][field])}" for row in bag))
        lines.append("};")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    root = Path(__file__).resolve().parents[2]
    out_dir = root / "results" / "A7-NATIVE-GRAPH" / "TERMGEN"
    out_dir.mkdir(parents=True, exist_ok=True)
    bag = build_bag()
    # Rival falsifier: host-composed partial terms would omit a family
    families = {
        "hamming": all("entity_match" in r["terms"] for r in bag),
        "relation_binding": all("relation_match" in r["terms"] for r in bag),
        "intent_context": all(
            "intent_match" in r["terms"] and "context_match" in r["terms"] for r in bag
        ),
        "path": all("path_confidence" in r["terms"] for r in bag),
    }
    if not all(families.values()):
        print("TERMGEN_PY_FAIL missing_family", families)
        return 2
    # Exact self-check on v0/v1 extremes
    t0 = bag[0]["terms"]
    if t0["entity_match"] != 64 or t0["path_confidence"] != 64:
        print("TERMGEN_PY_FAIL v0_max", t0)
        return 3
    t1 = bag[1]["terms"]
    if t1["entity_match"] != 0:
        print("TERMGEN_PY_FAIL v1_min", t1)
        return 4

    golden = {
        "law_id": LAW_ID,
        "seed": f"0x{SEED:08X}",
        "n_vectors": len(bag),
        "cue_w": CUE_W,
        "families": list(families.keys()),
        "dsp_preferred": 0,
        "board_pass": False,
        "vectors": bag,
    }
    # JSON: cues as hex strings for readability
    for row in golden["vectors"]:
        for k, v in list(row["cues"].items()):
            if k.endswith("_cue"):
                row["cues"][k] = f"0x{v:016X}"

    gpath = out_dir / "golden_termgen.json"
    gpath.write_text(json.dumps(golden, indent=2) + "\n", encoding="utf-8")
    sv_inc = root / "tests" / "xsim" / "tb_a7ng_termgen_golden.svh"
    # rebuild bag with int cues for SV emit
    bag_int = build_bag()
    emit_sv_include(bag_int, sv_inc)
    print(f"TERMGEN_PY_PASS law={LAW_ID} n={len(bag)} families={families}")
    print(f"golden={gpath}")
    print(f"svh={sv_inc}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
