// a7ng_astra_c2_persist_mig.sv — ASTRA-C2-PERSIST-MIG-01. PROGRAM=NO.
// New named DUT. Instantiates persist-commit KEEP. Does not edit KEEP / mig.prj / ddr3_model.
// ONE UNKNOWN: 20-bit persist identity + w0 survive on-chip clear and reload
// through official Digilent AXI MIG + ddr3_model after init_calib_complete.
`timescale 1ps / 1ps
`include "a7ng_astra_c2_persist_mig.svh"

module a7ng_astra_c2_persist_mig (
  input  logic        clk,
  input  logic        rst_n,
  input  logic        init_calib_complete_i,
  input  logic        persist_clr_i,
  input  logic        reload_i,
  input  logic        retire_i,
  input  logic        upd_valid_i,
  output logic        upd_ready_o,
  input  logic [19:0] upd_subj_i,
  input  logic [19:0] upd_rel_i,
  input  logic [19:0] upd_obj_i,
  input  logic [19:0] upd_ctx_i,
  input  logic [7:0]  upd_gen_i,
  input  logic [7:0]  upd_txn_i,
  input  logic [7:0]  upd_schema_i,
  input  logic signed [3:0] upd_rew_i,
  input  logic        lk_go_i,
  input  logic [19:0] lk_subj_i,
  input  logic [19:0] lk_rel_i,
  input  logic [19:0] lk_obj_i,
  input  logic [19:0] lk_ctx_i,
  output logic        lk_hit_o,
  output logic        busy_o,
  output logic [3:0]  phase_o,
  output logic [3:0]  fail_code_o,
  output logic signed [15:0] live_w0_o,
  output logic        persist_valid_o,
  output logic [19:0] persist_subj_o,
  output logic [19:0] persist_rel_o,
  output logic [19:0] persist_obj_o,
  output logic [19:0] persist_ctx_o,
  output logic [7:0]  persist_gen_o,
  output logic [7:0]  persist_txn_o,
  output logic [7:0]  persist_schema_o,
  output logic signed [15:0] persist_w0_o,
  output logic [15:0] n_upd_o,
  output logic [15:0] n_dup_o,
  output logic [15:0] n_stale_o,
  output logic [15:0] n_schema_o,
  output logic [15:0] n_false_o,
  output logic [3:0]  m_axi_awid,
  output logic [27:0] m_axi_awaddr,
  output logic [7:0]  m_axi_awlen,
  output logic [2:0]  m_axi_awsize,
  output logic [1:0]  m_axi_awburst,
  output logic        m_axi_awvalid,
  input  logic        m_axi_awready,
  output logic [127:0] m_axi_wdata,
  output logic [15:0] m_axi_wstrb,
  output logic        m_axi_wlast,
  output logic        m_axi_wvalid,
  input  logic        m_axi_wready,
  input  logic [3:0]  m_axi_bid,
  input  logic [1:0]  m_axi_bresp,
  input  logic        m_axi_bvalid,
  output logic        m_axi_bready,
  output logic [3:0]  m_axi_arid,
  output logic [27:0] m_axi_araddr,
  output logic [7:0]  m_axi_arlen,
  output logic [2:0]  m_axi_arsize,
  output logic [1:0]  m_axi_arburst,
  output logic        m_axi_arvalid,
  input  logic        m_axi_arready,
  input  logic [3:0]  m_axi_rid,
  input  logic [127:0] m_axi_rdata,
  input  logic [1:0]  m_axi_rresp,
  input  logic        m_axi_rlast,
  input  logic        m_axi_rvalid,
  output logic        m_axi_rready
);
  logic p_ready;
  logic go;

  assign go = init_calib_complete_i && rst_n;
  assign upd_ready_o = p_ready && go;

  a7ng_astra_c2_persist_commit u_id (
    .clk(clk), .rst_n(rst_n),
    .persist_clr_i(persist_clr_i), .reload_i(reload_i && go), .retire_i(retire_i),
    .upd_valid_i(upd_valid_i && go), .upd_ready_o(p_ready),
    .upd_subj_i(upd_subj_i), .upd_rel_i(upd_rel_i), .upd_obj_i(upd_obj_i),
    .upd_ctx_i(upd_ctx_i), .upd_gen_i(upd_gen_i), .upd_txn_i(upd_txn_i),
    .upd_schema_i(upd_schema_i), .upd_rew_i(upd_rew_i),
    .lk_go_i(lk_go_i), .lk_subj_i(lk_subj_i), .lk_rel_i(lk_rel_i),
    .lk_obj_i(lk_obj_i), .lk_ctx_i(lk_ctx_i), .lk_hit_o(lk_hit_o),
    .busy_o(busy_o), .phase_o(phase_o), .fail_code_o(fail_code_o),
    .live_w0_o(live_w0_o),
    .persist_valid_o(persist_valid_o),
    .persist_subj_o(persist_subj_o), .persist_rel_o(persist_rel_o),
    .persist_obj_o(persist_obj_o), .persist_ctx_o(persist_ctx_o),
    .persist_gen_o(persist_gen_o), .persist_txn_o(persist_txn_o),
    .persist_schema_o(persist_schema_o), .persist_w0_o(persist_w0_o),
    .n_upd_o(n_upd_o), .n_dup_o(n_dup_o), .n_stale_o(n_stale_o),
    .n_schema_o(n_schema_o), .n_false_o(n_false_o),
    .m_axi_awid(m_axi_awid), .m_axi_awaddr(m_axi_awaddr), .m_axi_awlen(m_axi_awlen),
    .m_axi_awsize(m_axi_awsize), .m_axi_awburst(m_axi_awburst),
    .m_axi_awvalid(m_axi_awvalid), .m_axi_awready(m_axi_awready),
    .m_axi_wdata(m_axi_wdata), .m_axi_wstrb(m_axi_wstrb), .m_axi_wlast(m_axi_wlast),
    .m_axi_wvalid(m_axi_wvalid), .m_axi_wready(m_axi_wready),
    .m_axi_bid(m_axi_bid), .m_axi_bresp(m_axi_bresp), .m_axi_bvalid(m_axi_bvalid),
    .m_axi_bready(m_axi_bready),
    .m_axi_arid(m_axi_arid), .m_axi_araddr(m_axi_araddr), .m_axi_arlen(m_axi_arlen),
    .m_axi_arsize(m_axi_arsize), .m_axi_arburst(m_axi_arburst),
    .m_axi_arvalid(m_axi_arvalid), .m_axi_arready(m_axi_arready),
    .m_axi_rid(m_axi_rid), .m_axi_rdata(m_axi_rdata), .m_axi_rresp(m_axi_rresp),
    .m_axi_rlast(m_axi_rlast), .m_axi_rvalid(m_axi_rvalid), .m_axi_rready(m_axi_rready)
  );
endmodule
