"""Emit frozen Q1 sign ROM + xsim test vectors. Does not retune the seed."""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from python.eam.qenc import D_MODEL, N_BITS, Q1_LAW, Q1_S, Q1_SEED, encode_q1  # noqa: E402

RTL = ROOT / "rtl" / "eam" / "eam02q_q1_signs.svh"
TV = ROOT / "tests" / "xsim" / "a7eam02q_q1_tv.svh"
MAN = ROOT / "results" / "A7-EAM-02Q" / "q1_rom.json"


def columns() -> list[int]:
    cols = [0] * D_MODEL
    for i, row in enumerate(Q1_S):
        for j, s in enumerate(row):
            if s > 0:
                cols[j] |= 1 << i
    return cols


def vectors() -> list[list[int]]:
    vs: list[list[int]] = [
        [0] * D_MODEL,
        [1] * D_MODEL,
        [-1] * D_MODEL,
        [32767] * D_MODEL,
        [-32768] * D_MODEL,
        [5 if (i % 3) else -3 for i in range(D_MODEL)],
        [i - 64 for i in range(D_MODEL)],
        [(-1) ** i * (i + 1) for i in range(D_MODEL)],
    ]
    for k in range(8):
        v = [((k * 17 + i * 13) % 401) - 200 for i in range(D_MODEL)]
        vs.append(v)
    return vs


def main() -> int:
    cols = columns()
    pop = sum(c.bit_count() for c in cols)
    lines = [
        "// AUTO-GENERATED by tools/gen_q1_rom.py — do not edit by hand.",
        f"// law {Q1_LAW} seed 32'h{Q1_SEED:08X}. Column j bit i = (s_ij == +1).",
        "localparam logic [63:0] Q1_COL [0:127] = '{",
    ]
    for j, c in enumerate(cols):
        comma = "," if j != 127 else ""
        lines.append(f"    64'h{c:016x}{comma}")
    lines.append("};")
    RTL.write_text("\n".join(lines) + "\n", encoding="utf-8")

    vs = vectors()
    keys = [encode_q1(v) for v in vs]
    tv = [
        "// AUTO-GENERATED Q1 test vectors. Host encode_q1 is the oracle.",
        f"localparam int Q1_TV_N = {len(vs)};",
        "localparam logic signed [15:0] Q1_TV_H [0:Q1_TV_N-1][0:127] = '{",
    ]
    for vi, v in enumerate(vs):
        inner = ", ".join(str(x) for x in v)
        comma = "," if vi != len(vs) - 1 else ""
        tv.append(f"    '{{{inner}}}{comma}")
    tv.append("};")
    tv.append("localparam logic [63:0] Q1_TV_KEY [0:Q1_TV_N-1] = '{")
    for vi, k in enumerate(keys):
        comma = "," if vi != len(keys) - 1 else ""
        tv.append(f"    64'h{k:016x}{comma}")
    tv.append("};")
    TV.parent.mkdir(parents=True, exist_ok=True)
    TV.write_text("\n".join(tv) + "\n", encoding="utf-8")

    MAN.parent.mkdir(parents=True, exist_ok=True)
    MAN.write_text(
        json.dumps(
            {
                "law": Q1_LAW,
                "seed": Q1_SEED,
                "plus_one_bits": pop,
                "n_tv": len(vs),
                "keys": [f"{k:016x}" for k in keys],
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"WROTE {RTL} plus1={pop}/8192")
    print(f"WROTE {TV} n={len(vs)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
